apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  volumes:
    - name: efs-storage
      persistentVolumeClaim:
        claimName: efs-claim
  containers:
    - name: efs-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: efs-storage



